FROM python:3.12-alpine3.19

RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --prefer-binary --retries 5 --timeout 30 -r /tmp/requirements.txt

WORKDIR /app
COPY . /app

EXPOSE 8099

CMD ["python", "-m", "app.main"]
